spring:
  application:
    name: crowd-data-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/WaterQualityMonitoring
  servlet:
    multipart:
      max-file-size: ${IMAGE_MAX_FILE_SIZE}
      max-request-size: ${IMAGE_MAX_REQUEST_SIZE}
server:
  port: ${SERVER_PORT}
api-gateway:
  url: ${GATEWAY_URL}

keycloak:
  server-url: http://localhost:8080
  realm: WaterQualityMonitoring
  client-id: main-service
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: FULL
logging:
  level:
    com.waterqualitymonitoring.crowdsourcedataservice.feignclient: DEBUG
    feign: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true